"use client";
import { Inter } from "next/font/google";
import React, { useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    // Dynamically import the Bootstrap JavaScript bundle
    //@ts-ignore
    import("bootstrap/dist/js/bootstrap.bundle.min.js")
      .then(() => {
        console.log("Bootstrap JS loaded");
      })
      .catch(err => console.error("Failed to load Bootstrap JS:", err));
  }, []);

  return (
    <html lang="en">
      <head>
        <title>Techpass</title>
        <meta name="description" content="Techpass" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
